### ISSUE TITLE
"Unhandled rejection TypeError: callback is not a function" when uploading

### ISSUE THREAD

**Issue by casvaniersel** [estruyf/gulp-spsync-creds#1]
Hey Elio I just came across an issue when trying to upload to my customers environment. I think they are using forefront TMG can that be a problem? 

This is the complete error:

[08:20:14] Using gulpfile G:\Klanten\DisplayTemplates\gulpfile.js
[08:20:14] Starting 'default'...
[08:20:14] Uploading _catalogs\masterpage\Item_Starter.html
Unhandled rejection TypeError: callback is not a function
    at Object.parseType2Message (G:\Klanten\DisplayTemplates\node_modules\httpntlm\ntlm.js:106:10)
    at G:\Klanten\DisplayTemplates\node_modules\sp-request\lib\src\core\auth\OnPremResolver.js:33:37
    at tryCatcher (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\async.js:148:10)

```
at Immediate.Async.drainQueues [as _onImmediate] (G:\Klanten\DisplayTemplates\node_modules\bluebird\js\release\async.js:17:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by estruyf** [comment]
Hi @casvaniersel,

I cannot test it, so if you want to help, here is something you can try.

In your project, can you update the gulp-spsync-creds - **fileSyncHelper.js** file (you can find it under node_modules) to include the domain. 

Change line 17: `this.spr = sprequest.create({ username: options.username, password: options.password });`

To this: `this.spr = sprequest.create({ username: options.username, password: options.password }, { domain: 'your-domain' });`

Let me know if this helps.

**Comment by casvaniersel** [comment]
Hey @estruyf tried it but it didn't solve the issue. The error remains and is exactly the same as posted here. When I have time I'll try to do a test from within the customers network to see if it's working.
