### ISSUE TITLE
Authentication Error on Upload

### ISSUE THREAD

**Issue by CharlieDLee** [estruyf/gulp-spsync-creds#11]
I have just recenlty upgraded an SPFx project to the latest version (1.3.0) and as part of this upgrade I have noticed that our implementation of gulp-spsync-creds is failing.

The gulp command being executed worked perfectly in the previous project, but now we seem to be getting an issue from the node-sp-auth package being used.

The error is as follows:
```
[11:50:47] Using gulpfile C:\Code\Engage\gulpfile.js
[11:50:47] Starting gulp
[11:50:47] Starting 'upload-to-sharepoint'...
[11:50:47] Uploading engage-announcements-bundle_cb402a50aabee4b1b5ecee43a35e546b.js
Unhandled rejection Error: Unable to resolve namespace authentiation type. Type received: Unknown
    at C:\Code\Engage\node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineUserCredentials.js:93:19
    at tryCatcher (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Code\Engage\node_modules\node-sp-auth\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

About to exit with code: 0
Process terminated before summary could be written, possible error in async code not continuing!
Trying to exit with exit code 1
```
 
Do I need to make some changes to ensure this package continues to work?  I have updated to the latest version of the package 2.3.7, but I still see the same issue.

**Comment by estruyf** [comment]
There seems to be an issue with the `node-sp-auth` module. Can you try to remove the `node_modules` folder and reinstall everything again? If that did not work, can you check the version which is installed of the `node-sp-auth` module?

**Comment by estruyf** [comment]
Just tested out the latest version, and I see no issues with it.

Can you also share your configuration?

**Comment by CharlieDLee** [comment]
I have just blown away my node_modules and done a full npm install.  Still seeing the same issue.

node-sp-auth is installed at version 2.2.9

gulpfile.js

```
'use strict';

const gulp = require('gulp');
const build = require('@microsoft/sp-build-web');
const spsync = require('gulp-spsync-creds').sync;
const fs = require('fs');

build.addSuppression('The local CSS class is not camelCase and will not be type-safe.')

build.task('upload-to-sharepoint', {
    execute: (config) => {
        return new Promise((resolve, reject) => {
            const deployFolder = require('./config/copy-assets.json');
            const folderLocation = `./${deployFolder.deployCdnPath}/**/*.js`;

            const username = config.args['username'] || "";
            const password = config.args['password'] || "";
            const site = config.args['site'] || "";
            const libraryPath = config.args['libraryPath'] || "";
            return gulp.src(folderLocation)
                .pipe(spsync({
                    "username": username,
                    "password": password,
                    "site": site,
                    "libraryPath": libraryPath,
                    "publish": true
                }))
                .on('finish', resolve);
        });
    }
});

build.task('upload-package-to-sharepoint', {
    execute: (config) => {
        return new Promise((resolve, reject) => {
            const packageSolution = require('./config/package-solution.json');
            const fileLocation = `./sharepoint/${packageSolution.paths.zippedPackage}`;

            const username = config.args['username'] || "";
            const password = config.args['password'] || "";
            const site = config.args['site'] || "";
            const libraryPath = config.args['libraryPath'] || "";
            return gulp.src(fileLocation)
                .pipe(spsync({
                    "username": username,
                    "password": password,
                    "site": site,
                    "libraryPath": libraryPath,
                    "publish": true
                }))
                .on('finish', resolve);
        });
    }
});

build.task('update-manifest', {
    execute: (config) => {
        return new Promise((resolve, reject) => {
            const cdnPath = config.args['cdnpath'] || "";
            let json = JSON.parse(fs.readFileSync('./config/write-manifests.json'));
            json.cdnBasePath = cdnPath;
            fs.writeFileSync('./config/write-manifests.json', JSON.stringify(json));
            resolve();
        });
    }
});

build.initialize(gulp);
```

Running this in my release pipeline with:

`gulp upload-to-sharepoint --ship --username xxx@xxx.onmicrosoft.com --password xxx --site https://xxx.sharepoint.com/sites/CDN --libraryPath CDN/xxx`

Anything else I should be trying?

**Comment by estruyf** [comment]
Configuration looks good, and the gulp command + arguments as well.

Do you also have this problem when you run it from your command prompt?

Does your password have any special characters especially the`&`. I recently found out that VSTS has problems with it.

**Comment by estruyf** [comment]
Just tried out a migration from version `1.0.0` to `1.3.0` and nothing changed to my upload process.

I see that you have `--libraryPath CDN/xxx`. Is `CDN` a library or is the `xxx` the library?

**Comment by CharlieDLee** [comment]
Yes same problem when running locally at command prompt.

xxx in the libraryPath is a folder inside a library called CDN, which is on a site collection at sites/CDN.

**Comment by estruyf** [comment]
Last idea, can you turn on verbose logging: `verbose: true`. On which point does it fail?

**Comment by CharlieDLee** [comment]
Just came back to look at this and please accept my humble _'fat fingered'_ apologies...it turns out our username was incorrectly specified in a keypass file and then in turn in the release configuration and in my command line calls. . .#mortified

**Comment by estruyf** [comment]
Thanks for the update!

**Comment by polashivaprasad** [comment]
i am getting below error when trying to access sharepoint.
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at getSecurityToken.then.then.data (H:\sample\node_modules\node-sp-auth\lib\
src\auth\resolvers\OnlineUserCredentials.js:54:63)
    at tryCatcher (H:\sample\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (H:\sample\node_modules\bluebird\js\rel
ease\promise.js:512:31)
    at Promise._settlePromise (H:\sample\node_modules\bluebird\js\release\promis
e.js:569:18)
    at Promise._settlePromise0 (H:\sample\node_modules\bluebird\js\release\promi
se.js:614:10)
    at Promise._settlePromises (H:\sample\node_modules\bluebird\js\release\promi
se.js:693:18)
    at Async._drainQueue (H:\sample\node_modules\bluebird\js\release\async.js:13
3:16)
    at Async._drainQueues (H:\sample\node_modules\bluebird\js\release\async.js:1
43:10)
    at Immediate.Async.drainQueues (H:\sample\node_modules\bluebird\js\release\a
sync.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)

**Comment by estruyf** [comment]
Seems to be an issue with the `node-sp-auth` module. Would you be able to test out the sample from the repo its homepage: https://github.com/s-KaiNet/node-sp-auth ?
